export const products =  [
    {
    id: 1,
    title: 'Pommes',
    type: 'Fruit',
    description: 'Pommes de la région de la Rioja',
    img:'../../assets/fruits/pommes.jpg',
    price: 2.5,
    },
    {
    id: 2,
    title: 'Bananes',
    type: 'Fruit',
    description: 'Bananes des îles Canaries',
    img:'../../assets/fruits/bananes.jpg',
    price: 1.99,
    },
    {
    id: 3,
    title: 'Oranges',
    type: 'Fruit',
    description: 'Oranges de Valence',
    img:'../../assets/fruits/oranges.jpg',
    price: 3.5,
    },
    {
    id: 4,
    title: 'Citrons',
    type: 'Fruit',
    description: 'Citrons de Murcie',
    img:'../../assets/fruits/citrons.jpg',
    price: 3.49,
    },
    {
    id: 5,
    title: 'Fraises',
    type: 'Fruit',
    description: 'Fraises de Huelva',
    img:'../../assets/fruits/fraises.jpg',
    price: 4.99,
    },
    {
    id: 6,
    title: 'Pastèque',
    type: 'Fruit',
    description: 'Pastèque de Murcie',
    img:'../../assets/fruits/pasteque.jpg',
    price: 3.49,
    },
    {
    id: 7,
    title: 'Raisin',
    type: 'Fruit',
    description: 'Raisin de la Rioja',
    img:'../../assets/fruits/raisin.jpg',
    price: 2.5,
    },
] 